// display order of the projects on the main page
export const ProjectOrder: string[] = [
  "holistic-health",
  "mark-12-30",
  "maybe-happy-ending",
  "cocktail-spots",
  "aletia-and-dino-adventures",
  "the-hijacking-of-creativity",

  "our-heroes-series",
  "national-park-series",
  "endangered-animals-pangolin",
  "sunk-cost",
  "family-tree",
  "first-to-post",
  "chinatown-pilgrimage",
  "living-with-grief",
  "book-covers-for-brandon-shewmake",
  "earring-advert",

  "hurl-at-camp-whurl",
  "iffy-eats-monsters",
  "digital-ocean",
  "mountain-lake-date",
  "pourtables-coffee-labels",
  "the-horse-the-hound-and-the-hare",
  "still-life-studies",
  "amanda-the-space-witch",
  // "relic-comic",
  "cocktails-and-tea",
  "griffith-fight-scene",
  "avo-ovo-deconstruction",
  "service-economy",
  "snowboarding-poster",
  "local-cafe-tea-tasting-poster",
  // "local-cafe-ingredient-list",
  "strawberry-jam-recipe",
  "walking-to-dinner-website",
];
