// display order of the projects on the main page
export const ProjectOrder: string[] = [
  "holistic-health",
  "snowboarding-poster",
  "the-hijacking-of-creativity",
  "service-economy",
  "sunk-cost",
  "cocktail-spots",
  "first-to-post",
  "avo-ovo-deconstruction",
  "earring-advert",
  "cassidys-strawberry-jam",
  "the-horse-the-hound-and-the-hare",
  "digital-ocean",
  "mountain-lake-date",
  "living-with-grief",
  "endangered-animals-pangolin",
  "pourtables-coffee-labels",

  "adventures-of-aletia",
  "our-heroes-series",
  "family-tree",
  "dino-adventures",
  "hurl-at-camp-whurl",
  "chinatown-pilgrimage",
  "iffy-eats-monsters",
  "amanda-the-space-witch",
  "relic-comic",
  "griffith-fight-scene",

  "national-park-series",
  "old-fashioned-advert",
  "hojicha-tea",
  "strawberry-jam-recipe",
  "avocado-hash-brown-deconstruction",
  "local-cafe-tea-tasting-poster",
  "ice",
  "book-covers-for-brandon-shewmake",
  "tangerines",
  "honey",
  "pourtables-coffee-line-art",
  "picnic-editorial-spread",
  "local-cafe-ingredient-list",
  "cosmopolitan",
];
